services:
  database:
    image: ijia/db
    container_name: ijia-db
    build:
      context: ./deps/ijia-data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust # 测试用
      POSTGRES_DB: ijia
      POSTGRES_USER: postgres
      # POSTGRES_PASSWORD: xxx
    ports:
      - 5442:5432 # e2e测试时 需要连接
  redis:
    image: redis:7.4.2-alpine

  web-api:
    image: ijia/web-api
    container_name: ijia-web-api
    depends_on:
      database:
        condition: service_started
      redis:
        condition: service_started
        restart: true
    build:
      context: .
      dockerfile: ./build/dockerfile.web-api
    environment:
      DATABASE_URL: "postgresql://ijia_web@database:5432/ijia"
      REDIS_CONNECT_URL: "redis://redis:6379"
      OSS_ROOT_DIR: "/data/oss"
      CHECK_SERVER: "localserver:9000"
      MODE: E2E
      JWT_KEY: 123
    extra_hosts:
      - localserver:host-gateway
    links:
      - redis
      - database
  web-nginx:
    image: ijia/web-nginx
    container_name: ijia-web-nginx
    build:
      context: .
      dockerfile: ./build/dockerfile.web
      args:
        - name=value
    links:
      - web-api:web_api
      - web-api:file_server
    ports:
      - "9001:443"
      - "9002:80"
