/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root.tsx'
import { Route as ThemeRouteRouteImport } from './routes/_theme/route.tsx'
import { Route as SchoolRouteRouteImport } from './routes/_school/route.tsx'
import { Route as StoryIndexRouteImport } from './routes/story/index.tsx'
import { Route as homeIndexRouteImport } from './routes/(home)/index.tsx'
import { Route as SchoolExaminationRouteRouteImport } from './routes/_school/examination/route.tsx'
import { Route as ThemeAboutIndexRouteImport } from './routes/_theme/about/index.tsx'
import { Route as SchoolWallIndexRouteImport } from './routes/_school/wall/index.tsx'
import { Route as SchoolUserIndexRouteImport } from './routes/_school/user/index.tsx'
import { Route as SchoolReviewIndexRouteImport } from './routes/_school/review/index.tsx'
import { Route as SchoolLiveIndexRouteImport } from './routes/_school/live/index.tsx'
import { Route as SchoolExaminationIndexRouteImport } from './routes/_school/examination/index.tsx'
import { Route as ThemeAboutIntroductionRouteImport } from './routes/_theme/about/introduction.tsx'
import { Route as ThemeAboutGuideRouteImport } from './routes/_theme/about/guide.tsx'
import { Route as SchoolWallPublishRouteImport } from './routes/_school/wall/publish.tsx'
import { Route as SchoolQuestionCreateRouteImport } from './routes/_school/question/create.tsx'
import { Route as SchoolProfileCenterRouteImport } from './routes/_school/profile/center.tsx'
import { Route as SchoolExaminationSimulateRouteImport } from './routes/_school/examination/simulate.tsx'
import { Route as SchoolUserUserIdRouteRouteImport } from './routes/_school/user/$userId/route.tsx'
import { Route as SchoolReviewTypeRouteRouteImport } from './routes/_school/review/$type/route.tsx'
import { Route as SchoolUserUserIdIndexRouteImport } from './routes/_school/user/$userId/index.tsx'
import { Route as SchoolReviewTypeIndexRouteImport } from './routes/_school/review/$type/index.tsx'
import { Route as SchoolExaminationSelfIndexRouteImport } from './routes/_school/examination/self/index.tsx'
import { Route as SchoolExaminationExamIdIndexRouteImport } from './routes/_school/examination/$examId/index.tsx'
import { Route as SchoolQuestionEditQuestionIdRouteImport } from './routes/_school/question/edit.$questionId.tsx'
import { Route as SchoolWallListChar123GroupIdChar125RouteRouteImport } from './routes/_school/wall/list.{-$groupId}/route.tsx'
import { Route as SchoolWallListChar123GroupIdChar125IndexRouteImport } from './routes/_school/wall/list.{-$groupId}/index.tsx'
import { Route as SchoolUserUserIdQuestionIndexRouteImport } from './routes/_school/user/$userId/question/index.tsx'
import { Route as SchoolUserUserIdPostIndexRouteImport } from './routes/_school/user/$userId/post/index.tsx'

const ThemeTestPageIndexLazyRouteImport =
  createFileRoute('/_theme/test-page/')()
const ThemeTestPageUploadLazyRouteImport = createFileRoute(
  '/_theme/test-page/upload',
)()

const ThemeRouteRoute = ThemeRouteRouteImport.update({
  id: '/_theme',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/_theme/route.lazy.tsx').then((d) => d.Route),
)
const SchoolRouteRoute = SchoolRouteRouteImport.update({
  id: '/_school',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/_school/route.lazy.tsx').then((d) => d.Route),
)
const StoryIndexRoute = StoryIndexRouteImport.update({
  id: '/story/',
  path: '/story/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/story/index.lazy.tsx').then((d) => d.Route),
)
const homeIndexRoute = homeIndexRouteImport
  .update({
    id: '/(home)/',
    path: '/',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(home)/index.lazy.tsx').then((d) => d.Route))
const SchoolExaminationRouteRoute = SchoolExaminationRouteRouteImport.update({
  id: '/examination',
  path: '/examination',
  getParentRoute: () => SchoolRouteRoute,
} as any).lazy(() =>
  import('./routes/_school/examination/route.lazy.tsx').then((d) => d.Route),
)
const ThemeTestPageIndexLazyRoute = ThemeTestPageIndexLazyRouteImport.update({
  id: '/test-page/',
  path: '/test-page/',
  getParentRoute: () => ThemeRouteRoute,
} as any).lazy(() =>
  import('./routes/_theme/test-page/index.lazy.tsx').then((d) => d.Route),
)
const ThemeAboutIndexRoute = ThemeAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => ThemeRouteRoute,
} as any).lazy(() =>
  import('./routes/_theme/about/index.lazy.tsx').then((d) => d.Route),
)
const SchoolWallIndexRoute = SchoolWallIndexRouteImport.update({
  id: '/wall/',
  path: '/wall/',
  getParentRoute: () => SchoolRouteRoute,
} as any)
const SchoolUserIndexRoute = SchoolUserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => SchoolRouteRoute,
} as any)
const SchoolReviewIndexRoute = SchoolReviewIndexRouteImport.update({
  id: '/review/',
  path: '/review/',
  getParentRoute: () => SchoolRouteRoute,
} as any)
const SchoolLiveIndexRoute = SchoolLiveIndexRouteImport.update({
  id: '/live/',
  path: '/live/',
  getParentRoute: () => SchoolRouteRoute,
} as any).lazy(() =>
  import('./routes/_school/live/index.lazy.tsx').then((d) => d.Route),
)
const SchoolExaminationIndexRoute = SchoolExaminationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SchoolExaminationRouteRoute,
} as any)
const ThemeTestPageUploadLazyRoute = ThemeTestPageUploadLazyRouteImport.update({
  id: '/test-page/upload',
  path: '/test-page/upload',
  getParentRoute: () => ThemeRouteRoute,
} as any).lazy(() =>
  import('./routes/_theme/test-page/upload.lazy.tsx').then((d) => d.Route),
)
const ThemeAboutIntroductionRoute = ThemeAboutIntroductionRouteImport.update({
  id: '/about/introduction',
  path: '/about/introduction',
  getParentRoute: () => ThemeRouteRoute,
} as any).lazy(() =>
  import('./routes/_theme/about/introduction.lazy.tsx').then((d) => d.Route),
)
const ThemeAboutGuideRoute = ThemeAboutGuideRouteImport.update({
  id: '/about/guide',
  path: '/about/guide',
  getParentRoute: () => ThemeRouteRoute,
} as any).lazy(() =>
  import('./routes/_theme/about/guide.lazy.tsx').then((d) => d.Route),
)
const SchoolWallPublishRoute = SchoolWallPublishRouteImport.update({
  id: '/wall/publish',
  path: '/wall/publish',
  getParentRoute: () => SchoolRouteRoute,
} as any).lazy(() =>
  import('./routes/_school/wall/publish.lazy.tsx').then((d) => d.Route),
)
const SchoolQuestionCreateRoute = SchoolQuestionCreateRouteImport.update({
  id: '/question/create',
  path: '/question/create',
  getParentRoute: () => SchoolRouteRoute,
} as any).lazy(() =>
  import('./routes/_school/question/create.lazy.tsx').then((d) => d.Route),
)
const SchoolProfileCenterRoute = SchoolProfileCenterRouteImport.update({
  id: '/profile/center',
  path: '/profile/center',
  getParentRoute: () => SchoolRouteRoute,
} as any).lazy(() =>
  import('./routes/_school/profile/center.lazy.tsx').then((d) => d.Route),
)
const SchoolExaminationSimulateRoute =
  SchoolExaminationSimulateRouteImport.update({
    id: '/simulate',
    path: '/simulate',
    getParentRoute: () => SchoolExaminationRouteRoute,
  } as any).lazy(() =>
    import('./routes/_school/examination/simulate.lazy.tsx').then(
      (d) => d.Route,
    ),
  )
const SchoolUserUserIdRouteRoute = SchoolUserUserIdRouteRouteImport.update({
  id: '/user/$userId',
  path: '/user/$userId',
  getParentRoute: () => SchoolRouteRoute,
} as any)
const SchoolReviewTypeRouteRoute = SchoolReviewTypeRouteRouteImport.update({
  id: '/review/$type',
  path: '/review/$type',
  getParentRoute: () => SchoolRouteRoute,
} as any)
const SchoolUserUserIdIndexRoute = SchoolUserUserIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SchoolUserUserIdRouteRoute,
} as any)
const SchoolReviewTypeIndexRoute = SchoolReviewTypeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SchoolReviewTypeRouteRoute,
} as any).lazy(() =>
  import('./routes/_school/review/$type/index.lazy.tsx').then((d) => d.Route),
)
const SchoolExaminationSelfIndexRoute =
  SchoolExaminationSelfIndexRouteImport.update({
    id: '/self/',
    path: '/self/',
    getParentRoute: () => SchoolExaminationRouteRoute,
  } as any).lazy(() =>
    import('./routes/_school/examination/self/index.lazy.tsx').then(
      (d) => d.Route,
    ),
  )
const SchoolExaminationExamIdIndexRoute =
  SchoolExaminationExamIdIndexRouteImport.update({
    id: '/$examId/',
    path: '/$examId/',
    getParentRoute: () => SchoolExaminationRouteRoute,
  } as any)
const SchoolQuestionEditQuestionIdRoute =
  SchoolQuestionEditQuestionIdRouteImport.update({
    id: '/question/edit/$questionId',
    path: '/question/edit/$questionId',
    getParentRoute: () => SchoolRouteRoute,
  } as any).lazy(() =>
    import('./routes/_school/question/edit.$questionId.lazy.tsx').then(
      (d) => d.Route,
    ),
  )
const SchoolWallListChar123GroupIdChar125RouteRoute =
  SchoolWallListChar123GroupIdChar125RouteRouteImport.update({
    id: '/wall/list/{-$groupId}',
    path: '/wall/list/{-$groupId}',
    getParentRoute: () => SchoolRouteRoute,
  } as any).lazy(() =>
    import('./routes/_school/wall/list.{-$groupId}/route.lazy.tsx').then(
      (d) => d.Route,
    ),
  )
const SchoolWallListChar123GroupIdChar125IndexRoute =
  SchoolWallListChar123GroupIdChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SchoolWallListChar123GroupIdChar125RouteRoute,
  } as any).lazy(() =>
    import('./routes/_school/wall/list.{-$groupId}/index.lazy.tsx').then(
      (d) => d.Route,
    ),
  )
const SchoolUserUserIdQuestionIndexRoute =
  SchoolUserUserIdQuestionIndexRouteImport.update({
    id: '/question/',
    path: '/question/',
    getParentRoute: () => SchoolUserUserIdRouteRoute,
  } as any).lazy(() =>
    import('./routes/_school/user/$userId/question/index.lazy.tsx').then(
      (d) => d.Route,
    ),
  )
const SchoolUserUserIdPostIndexRoute =
  SchoolUserUserIdPostIndexRouteImport.update({
    id: '/post/',
    path: '/post/',
    getParentRoute: () => SchoolUserUserIdRouteRoute,
  } as any).lazy(() =>
    import('./routes/_school/user/$userId/post/index.lazy.tsx').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof homeIndexRoute
  '/examination': typeof SchoolExaminationRouteRouteWithChildren
  '/story/': typeof StoryIndexRoute
  '/review/$type': typeof SchoolReviewTypeRouteRouteWithChildren
  '/user/$userId': typeof SchoolUserUserIdRouteRouteWithChildren
  '/examination/simulate': typeof SchoolExaminationSimulateRoute
  '/profile/center': typeof SchoolProfileCenterRoute
  '/question/create': typeof SchoolQuestionCreateRoute
  '/wall/publish': typeof SchoolWallPublishRoute
  '/about/guide': typeof ThemeAboutGuideRoute
  '/about/introduction': typeof ThemeAboutIntroductionRoute
  '/test-page/upload': typeof ThemeTestPageUploadLazyRoute
  '/examination/': typeof SchoolExaminationIndexRoute
  '/live/': typeof SchoolLiveIndexRoute
  '/review/': typeof SchoolReviewIndexRoute
  '/user/': typeof SchoolUserIndexRoute
  '/wall/': typeof SchoolWallIndexRoute
  '/about/': typeof ThemeAboutIndexRoute
  '/test-page/': typeof ThemeTestPageIndexLazyRoute
  '/wall/list/{-$groupId}': typeof SchoolWallListChar123GroupIdChar125RouteRouteWithChildren
  '/question/edit/$questionId': typeof SchoolQuestionEditQuestionIdRoute
  '/examination/$examId/': typeof SchoolExaminationExamIdIndexRoute
  '/examination/self/': typeof SchoolExaminationSelfIndexRoute
  '/review/$type/': typeof SchoolReviewTypeIndexRoute
  '/user/$userId/': typeof SchoolUserUserIdIndexRoute
  '/user/$userId/post/': typeof SchoolUserUserIdPostIndexRoute
  '/user/$userId/question/': typeof SchoolUserUserIdQuestionIndexRoute
  '/wall/list/{-$groupId}/': typeof SchoolWallListChar123GroupIdChar125IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof homeIndexRoute
  '/story': typeof StoryIndexRoute
  '/examination/simulate': typeof SchoolExaminationSimulateRoute
  '/profile/center': typeof SchoolProfileCenterRoute
  '/question/create': typeof SchoolQuestionCreateRoute
  '/wall/publish': typeof SchoolWallPublishRoute
  '/about/guide': typeof ThemeAboutGuideRoute
  '/about/introduction': typeof ThemeAboutIntroductionRoute
  '/test-page/upload': typeof ThemeTestPageUploadLazyRoute
  '/examination': typeof SchoolExaminationIndexRoute
  '/live': typeof SchoolLiveIndexRoute
  '/review': typeof SchoolReviewIndexRoute
  '/user': typeof SchoolUserIndexRoute
  '/wall': typeof SchoolWallIndexRoute
  '/about': typeof ThemeAboutIndexRoute
  '/test-page': typeof ThemeTestPageIndexLazyRoute
  '/question/edit/$questionId': typeof SchoolQuestionEditQuestionIdRoute
  '/examination/$examId': typeof SchoolExaminationExamIdIndexRoute
  '/examination/self': typeof SchoolExaminationSelfIndexRoute
  '/review/$type': typeof SchoolReviewTypeIndexRoute
  '/user/$userId': typeof SchoolUserUserIdIndexRoute
  '/user/$userId/post': typeof SchoolUserUserIdPostIndexRoute
  '/user/$userId/question': typeof SchoolUserUserIdQuestionIndexRoute
  '/wall/list/{-$groupId}': typeof SchoolWallListChar123GroupIdChar125IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_school': typeof SchoolRouteRouteWithChildren
  '/_theme': typeof ThemeRouteRouteWithChildren
  '/_school/examination': typeof SchoolExaminationRouteRouteWithChildren
  '/(home)/': typeof homeIndexRoute
  '/story/': typeof StoryIndexRoute
  '/_school/review/$type': typeof SchoolReviewTypeRouteRouteWithChildren
  '/_school/user/$userId': typeof SchoolUserUserIdRouteRouteWithChildren
  '/_school/examination/simulate': typeof SchoolExaminationSimulateRoute
  '/_school/profile/center': typeof SchoolProfileCenterRoute
  '/_school/question/create': typeof SchoolQuestionCreateRoute
  '/_school/wall/publish': typeof SchoolWallPublishRoute
  '/_theme/about/guide': typeof ThemeAboutGuideRoute
  '/_theme/about/introduction': typeof ThemeAboutIntroductionRoute
  '/_theme/test-page/upload': typeof ThemeTestPageUploadLazyRoute
  '/_school/examination/': typeof SchoolExaminationIndexRoute
  '/_school/live/': typeof SchoolLiveIndexRoute
  '/_school/review/': typeof SchoolReviewIndexRoute
  '/_school/user/': typeof SchoolUserIndexRoute
  '/_school/wall/': typeof SchoolWallIndexRoute
  '/_theme/about/': typeof ThemeAboutIndexRoute
  '/_theme/test-page/': typeof ThemeTestPageIndexLazyRoute
  '/_school/wall/list/{-$groupId}': typeof SchoolWallListChar123GroupIdChar125RouteRouteWithChildren
  '/_school/question/edit/$questionId': typeof SchoolQuestionEditQuestionIdRoute
  '/_school/examination/$examId/': typeof SchoolExaminationExamIdIndexRoute
  '/_school/examination/self/': typeof SchoolExaminationSelfIndexRoute
  '/_school/review/$type/': typeof SchoolReviewTypeIndexRoute
  '/_school/user/$userId/': typeof SchoolUserUserIdIndexRoute
  '/_school/user/$userId/post/': typeof SchoolUserUserIdPostIndexRoute
  '/_school/user/$userId/question/': typeof SchoolUserUserIdQuestionIndexRoute
  '/_school/wall/list/{-$groupId}/': typeof SchoolWallListChar123GroupIdChar125IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/examination'
    | '/story/'
    | '/review/$type'
    | '/user/$userId'
    | '/examination/simulate'
    | '/profile/center'
    | '/question/create'
    | '/wall/publish'
    | '/about/guide'
    | '/about/introduction'
    | '/test-page/upload'
    | '/examination/'
    | '/live/'
    | '/review/'
    | '/user/'
    | '/wall/'
    | '/about/'
    | '/test-page/'
    | '/wall/list/{-$groupId}'
    | '/question/edit/$questionId'
    | '/examination/$examId/'
    | '/examination/self/'
    | '/review/$type/'
    | '/user/$userId/'
    | '/user/$userId/post/'
    | '/user/$userId/question/'
    | '/wall/list/{-$groupId}/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/story'
    | '/examination/simulate'
    | '/profile/center'
    | '/question/create'
    | '/wall/publish'
    | '/about/guide'
    | '/about/introduction'
    | '/test-page/upload'
    | '/examination'
    | '/live'
    | '/review'
    | '/user'
    | '/wall'
    | '/about'
    | '/test-page'
    | '/question/edit/$questionId'
    | '/examination/$examId'
    | '/examination/self'
    | '/review/$type'
    | '/user/$userId'
    | '/user/$userId/post'
    | '/user/$userId/question'
    | '/wall/list/{-$groupId}'
  id:
    | '__root__'
    | '/_school'
    | '/_theme'
    | '/_school/examination'
    | '/(home)/'
    | '/story/'
    | '/_school/review/$type'
    | '/_school/user/$userId'
    | '/_school/examination/simulate'
    | '/_school/profile/center'
    | '/_school/question/create'
    | '/_school/wall/publish'
    | '/_theme/about/guide'
    | '/_theme/about/introduction'
    | '/_theme/test-page/upload'
    | '/_school/examination/'
    | '/_school/live/'
    | '/_school/review/'
    | '/_school/user/'
    | '/_school/wall/'
    | '/_theme/about/'
    | '/_theme/test-page/'
    | '/_school/wall/list/{-$groupId}'
    | '/_school/question/edit/$questionId'
    | '/_school/examination/$examId/'
    | '/_school/examination/self/'
    | '/_school/review/$type/'
    | '/_school/user/$userId/'
    | '/_school/user/$userId/post/'
    | '/_school/user/$userId/question/'
    | '/_school/wall/list/{-$groupId}/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SchoolRouteRoute: typeof SchoolRouteRouteWithChildren
  ThemeRouteRoute: typeof ThemeRouteRouteWithChildren
  homeIndexRoute: typeof homeIndexRoute
  StoryIndexRoute: typeof StoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_theme': {
      id: '/_theme'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ThemeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_school': {
      id: '/_school'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SchoolRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/': {
      id: '/story/'
      path: '/story'
      fullPath: '/story/'
      preLoaderRoute: typeof StoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_school/examination': {
      id: '/_school/examination'
      path: '/examination'
      fullPath: '/examination'
      preLoaderRoute: typeof SchoolExaminationRouteRouteImport
      parentRoute: typeof SchoolRouteRoute
    }
    '/_theme/test-page/': {
      id: '/_theme/test-page/'
      path: '/test-page'
      fullPath: '/test-page/'
      preLoaderRoute: typeof ThemeTestPageIndexLazyRouteImport
      parentRoute: typeof ThemeRouteRoute
    }
    '/_theme/about/': {
      id: '/_theme/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof ThemeAboutIndexRouteImport
      parentRoute: typeof ThemeRouteRoute
    }
    '/_school/wall/': {
      id: '/_school/wall/'
      path: '/wall'
      fullPath: '/wall/'
      preLoaderRoute: typeof SchoolWallIndexRouteImport
      parentRoute: typeof SchoolRouteRoute
    }
    '/_school/user/': {
      id: '/_school/user/'
      path: '/user'
      fullPath: '/user/'
      preLoaderRoute: typeof SchoolUserIndexRouteImport
      parentRoute: typeof SchoolRouteRoute
    }
    '/_school/review/': {
      id: '/_school/review/'
      path: '/review'
      fullPath: '/review/'
      preLoaderRoute: typeof SchoolReviewIndexRouteImport
      parentRoute: typeof SchoolRouteRoute
    }
    '/_school/live/': {
      id: '/_school/live/'
      path: '/live'
      fullPath: '/live/'
      preLoaderRoute: typeof SchoolLiveIndexRouteImport
      parentRoute: typeof SchoolRouteRoute
    }
    '/_school/examination/': {
      id: '/_school/examination/'
      path: '/'
      fullPath: '/examination/'
      preLoaderRoute: typeof SchoolExaminationIndexRouteImport
      parentRoute: typeof SchoolExaminationRouteRoute
    }
    '/_theme/test-page/upload': {
      id: '/_theme/test-page/upload'
      path: '/test-page/upload'
      fullPath: '/test-page/upload'
      preLoaderRoute: typeof ThemeTestPageUploadLazyRouteImport
      parentRoute: typeof ThemeRouteRoute
    }
    '/_theme/about/introduction': {
      id: '/_theme/about/introduction'
      path: '/about/introduction'
      fullPath: '/about/introduction'
      preLoaderRoute: typeof ThemeAboutIntroductionRouteImport
      parentRoute: typeof ThemeRouteRoute
    }
    '/_theme/about/guide': {
      id: '/_theme/about/guide'
      path: '/about/guide'
      fullPath: '/about/guide'
      preLoaderRoute: typeof ThemeAboutGuideRouteImport
      parentRoute: typeof ThemeRouteRoute
    }
    '/_school/wall/publish': {
      id: '/_school/wall/publish'
      path: '/wall/publish'
      fullPath: '/wall/publish'
      preLoaderRoute: typeof SchoolWallPublishRouteImport
      parentRoute: typeof SchoolRouteRoute
    }
    '/_school/question/create': {
      id: '/_school/question/create'
      path: '/question/create'
      fullPath: '/question/create'
      preLoaderRoute: typeof SchoolQuestionCreateRouteImport
      parentRoute: typeof SchoolRouteRoute
    }
    '/_school/profile/center': {
      id: '/_school/profile/center'
      path: '/profile/center'
      fullPath: '/profile/center'
      preLoaderRoute: typeof SchoolProfileCenterRouteImport
      parentRoute: typeof SchoolRouteRoute
    }
    '/_school/examination/simulate': {
      id: '/_school/examination/simulate'
      path: '/simulate'
      fullPath: '/examination/simulate'
      preLoaderRoute: typeof SchoolExaminationSimulateRouteImport
      parentRoute: typeof SchoolExaminationRouteRoute
    }
    '/_school/user/$userId': {
      id: '/_school/user/$userId'
      path: '/user/$userId'
      fullPath: '/user/$userId'
      preLoaderRoute: typeof SchoolUserUserIdRouteRouteImport
      parentRoute: typeof SchoolRouteRoute
    }
    '/_school/review/$type': {
      id: '/_school/review/$type'
      path: '/review/$type'
      fullPath: '/review/$type'
      preLoaderRoute: typeof SchoolReviewTypeRouteRouteImport
      parentRoute: typeof SchoolRouteRoute
    }
    '/_school/user/$userId/': {
      id: '/_school/user/$userId/'
      path: '/'
      fullPath: '/user/$userId/'
      preLoaderRoute: typeof SchoolUserUserIdIndexRouteImport
      parentRoute: typeof SchoolUserUserIdRouteRoute
    }
    '/_school/review/$type/': {
      id: '/_school/review/$type/'
      path: '/'
      fullPath: '/review/$type/'
      preLoaderRoute: typeof SchoolReviewTypeIndexRouteImport
      parentRoute: typeof SchoolReviewTypeRouteRoute
    }
    '/_school/examination/self/': {
      id: '/_school/examination/self/'
      path: '/self'
      fullPath: '/examination/self/'
      preLoaderRoute: typeof SchoolExaminationSelfIndexRouteImport
      parentRoute: typeof SchoolExaminationRouteRoute
    }
    '/_school/examination/$examId/': {
      id: '/_school/examination/$examId/'
      path: '/$examId'
      fullPath: '/examination/$examId/'
      preLoaderRoute: typeof SchoolExaminationExamIdIndexRouteImport
      parentRoute: typeof SchoolExaminationRouteRoute
    }
    '/_school/question/edit/$questionId': {
      id: '/_school/question/edit/$questionId'
      path: '/question/edit/$questionId'
      fullPath: '/question/edit/$questionId'
      preLoaderRoute: typeof SchoolQuestionEditQuestionIdRouteImport
      parentRoute: typeof SchoolRouteRoute
    }
    '/_school/wall/list/{-$groupId}': {
      id: '/_school/wall/list/{-$groupId}'
      path: '/wall/list/{-$groupId}'
      fullPath: '/wall/list/{-$groupId}'
      preLoaderRoute: typeof SchoolWallListChar123GroupIdChar125RouteRouteImport
      parentRoute: typeof SchoolRouteRoute
    }
    '/_school/wall/list/{-$groupId}/': {
      id: '/_school/wall/list/{-$groupId}/'
      path: '/'
      fullPath: '/wall/list/{-$groupId}/'
      preLoaderRoute: typeof SchoolWallListChar123GroupIdChar125IndexRouteImport
      parentRoute: typeof SchoolWallListChar123GroupIdChar125RouteRoute
    }
    '/_school/user/$userId/question/': {
      id: '/_school/user/$userId/question/'
      path: '/question'
      fullPath: '/user/$userId/question/'
      preLoaderRoute: typeof SchoolUserUserIdQuestionIndexRouteImport
      parentRoute: typeof SchoolUserUserIdRouteRoute
    }
    '/_school/user/$userId/post/': {
      id: '/_school/user/$userId/post/'
      path: '/post'
      fullPath: '/user/$userId/post/'
      preLoaderRoute: typeof SchoolUserUserIdPostIndexRouteImport
      parentRoute: typeof SchoolUserUserIdRouteRoute
    }
  }
}

interface SchoolExaminationRouteRouteChildren {
  SchoolExaminationSimulateRoute: typeof SchoolExaminationSimulateRoute
  SchoolExaminationIndexRoute: typeof SchoolExaminationIndexRoute
  SchoolExaminationExamIdIndexRoute: typeof SchoolExaminationExamIdIndexRoute
  SchoolExaminationSelfIndexRoute: typeof SchoolExaminationSelfIndexRoute
}

const SchoolExaminationRouteRouteChildren: SchoolExaminationRouteRouteChildren =
  {
    SchoolExaminationSimulateRoute: SchoolExaminationSimulateRoute,
    SchoolExaminationIndexRoute: SchoolExaminationIndexRoute,
    SchoolExaminationExamIdIndexRoute: SchoolExaminationExamIdIndexRoute,
    SchoolExaminationSelfIndexRoute: SchoolExaminationSelfIndexRoute,
  }

const SchoolExaminationRouteRouteWithChildren =
  SchoolExaminationRouteRoute._addFileChildren(
    SchoolExaminationRouteRouteChildren,
  )

interface SchoolReviewTypeRouteRouteChildren {
  SchoolReviewTypeIndexRoute: typeof SchoolReviewTypeIndexRoute
}

const SchoolReviewTypeRouteRouteChildren: SchoolReviewTypeRouteRouteChildren = {
  SchoolReviewTypeIndexRoute: SchoolReviewTypeIndexRoute,
}

const SchoolReviewTypeRouteRouteWithChildren =
  SchoolReviewTypeRouteRoute._addFileChildren(
    SchoolReviewTypeRouteRouteChildren,
  )

interface SchoolUserUserIdRouteRouteChildren {
  SchoolUserUserIdIndexRoute: typeof SchoolUserUserIdIndexRoute
  SchoolUserUserIdPostIndexRoute: typeof SchoolUserUserIdPostIndexRoute
  SchoolUserUserIdQuestionIndexRoute: typeof SchoolUserUserIdQuestionIndexRoute
}

const SchoolUserUserIdRouteRouteChildren: SchoolUserUserIdRouteRouteChildren = {
  SchoolUserUserIdIndexRoute: SchoolUserUserIdIndexRoute,
  SchoolUserUserIdPostIndexRoute: SchoolUserUserIdPostIndexRoute,
  SchoolUserUserIdQuestionIndexRoute: SchoolUserUserIdQuestionIndexRoute,
}

const SchoolUserUserIdRouteRouteWithChildren =
  SchoolUserUserIdRouteRoute._addFileChildren(
    SchoolUserUserIdRouteRouteChildren,
  )

interface SchoolWallListChar123GroupIdChar125RouteRouteChildren {
  SchoolWallListChar123GroupIdChar125IndexRoute: typeof SchoolWallListChar123GroupIdChar125IndexRoute
}

const SchoolWallListChar123GroupIdChar125RouteRouteChildren: SchoolWallListChar123GroupIdChar125RouteRouteChildren =
  {
    SchoolWallListChar123GroupIdChar125IndexRoute:
      SchoolWallListChar123GroupIdChar125IndexRoute,
  }

const SchoolWallListChar123GroupIdChar125RouteRouteWithChildren =
  SchoolWallListChar123GroupIdChar125RouteRoute._addFileChildren(
    SchoolWallListChar123GroupIdChar125RouteRouteChildren,
  )

interface SchoolRouteRouteChildren {
  SchoolExaminationRouteRoute: typeof SchoolExaminationRouteRouteWithChildren
  SchoolReviewTypeRouteRoute: typeof SchoolReviewTypeRouteRouteWithChildren
  SchoolUserUserIdRouteRoute: typeof SchoolUserUserIdRouteRouteWithChildren
  SchoolProfileCenterRoute: typeof SchoolProfileCenterRoute
  SchoolQuestionCreateRoute: typeof SchoolQuestionCreateRoute
  SchoolWallPublishRoute: typeof SchoolWallPublishRoute
  SchoolLiveIndexRoute: typeof SchoolLiveIndexRoute
  SchoolReviewIndexRoute: typeof SchoolReviewIndexRoute
  SchoolUserIndexRoute: typeof SchoolUserIndexRoute
  SchoolWallIndexRoute: typeof SchoolWallIndexRoute
  SchoolWallListChar123GroupIdChar125RouteRoute: typeof SchoolWallListChar123GroupIdChar125RouteRouteWithChildren
  SchoolQuestionEditQuestionIdRoute: typeof SchoolQuestionEditQuestionIdRoute
}

const SchoolRouteRouteChildren: SchoolRouteRouteChildren = {
  SchoolExaminationRouteRoute: SchoolExaminationRouteRouteWithChildren,
  SchoolReviewTypeRouteRoute: SchoolReviewTypeRouteRouteWithChildren,
  SchoolUserUserIdRouteRoute: SchoolUserUserIdRouteRouteWithChildren,
  SchoolProfileCenterRoute: SchoolProfileCenterRoute,
  SchoolQuestionCreateRoute: SchoolQuestionCreateRoute,
  SchoolWallPublishRoute: SchoolWallPublishRoute,
  SchoolLiveIndexRoute: SchoolLiveIndexRoute,
  SchoolReviewIndexRoute: SchoolReviewIndexRoute,
  SchoolUserIndexRoute: SchoolUserIndexRoute,
  SchoolWallIndexRoute: SchoolWallIndexRoute,
  SchoolWallListChar123GroupIdChar125RouteRoute:
    SchoolWallListChar123GroupIdChar125RouteRouteWithChildren,
  SchoolQuestionEditQuestionIdRoute: SchoolQuestionEditQuestionIdRoute,
}

const SchoolRouteRouteWithChildren = SchoolRouteRoute._addFileChildren(
  SchoolRouteRouteChildren,
)

interface ThemeRouteRouteChildren {
  ThemeAboutGuideRoute: typeof ThemeAboutGuideRoute
  ThemeAboutIntroductionRoute: typeof ThemeAboutIntroductionRoute
  ThemeTestPageUploadLazyRoute: typeof ThemeTestPageUploadLazyRoute
  ThemeAboutIndexRoute: typeof ThemeAboutIndexRoute
  ThemeTestPageIndexLazyRoute: typeof ThemeTestPageIndexLazyRoute
}

const ThemeRouteRouteChildren: ThemeRouteRouteChildren = {
  ThemeAboutGuideRoute: ThemeAboutGuideRoute,
  ThemeAboutIntroductionRoute: ThemeAboutIntroductionRoute,
  ThemeTestPageUploadLazyRoute: ThemeTestPageUploadLazyRoute,
  ThemeAboutIndexRoute: ThemeAboutIndexRoute,
  ThemeTestPageIndexLazyRoute: ThemeTestPageIndexLazyRoute,
}

const ThemeRouteRouteWithChildren = ThemeRouteRoute._addFileChildren(
  ThemeRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SchoolRouteRoute: SchoolRouteRouteWithChildren,
  ThemeRouteRoute: ThemeRouteRouteWithChildren,
  homeIndexRoute: homeIndexRoute,
  StoryIndexRoute: StoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
