/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root.tsx'
import { Route as EmptyRouteImport } from './routes/empty.tsx'
import { Route as SchoolRouteRouteImport } from './routes/_school/route.tsx'
import { Route as StoryIndexRouteImport } from './routes/story/index.tsx'
import { Route as AboutIndexRouteImport } from './routes/about/index.tsx'
import { Route as homeIndexRouteImport } from './routes/(home)/index.tsx'
import { Route as PassportFindAccountRouteImport } from './routes/passport/find-account.tsx'
import { Route as AboutIntroductionRouteImport } from './routes/about/introduction.tsx'
import { Route as AboutGuideRouteImport } from './routes/about/guide.tsx'
import { Route as PassportVideo_backgroundRouteRouteImport } from './routes/passport/_video_background/route.tsx'
import { Route as SchoolWallIndexRouteImport } from './routes/_school/wall/index.tsx'
import { Route as SchoolLiveIndexRouteImport } from './routes/_school/live/index.tsx'
import { Route as PassportVideo_backgroundSignupRouteImport } from './routes/passport/_video_background/signup.tsx'
import { Route as PassportVideo_backgroundLoginRouteImport } from './routes/passport/_video_background/login.tsx'
import { Route as SchoolWallPublishRouteImport } from './routes/_school/wall/publish.tsx'
import { Route as SchoolProfileSecurityRouteImport } from './routes/_school/profile/security.tsx'
import { Route as SchoolProfileCenterRouteImport } from './routes/_school/profile/center.tsx'
import { Route as SchoolExaminationSplatRouteImport } from './routes/_school/examination/$.tsx'
import { Route as SchoolWallListRouteRouteImport } from './routes/_school/wall/list/route.tsx'
import { Route as SchoolWallReviewIndexRouteImport } from './routes/_school/wall/review/index.tsx'
import { Route as SchoolWallListChar123GroupIdChar125RouteImport } from './routes/_school/wall/list/{-$groupId}.tsx'

const PassportRouteImport = createFileRoute('/passport')()

const PassportRoute = PassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => rootRouteImport,
} as any)
const EmptyRoute = EmptyRouteImport.update({
  id: '/empty',
  path: '/empty',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolRouteRoute = SchoolRouteRouteImport.update({
  id: '/_school',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/_school/route.lazy.tsx').then((d) => d.Route),
)
const StoryIndexRoute = StoryIndexRouteImport.update({
  id: '/story/',
  path: '/story/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/about/index.lazy.tsx').then((d) => d.Route),
)
const homeIndexRoute = homeIndexRouteImport
  .update({
    id: '/(home)/',
    path: '/',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(home)/index.lazy.tsx').then((d) => d.Route))
const PassportFindAccountRoute = PassportFindAccountRouteImport.update({
  id: '/find-account',
  path: '/find-account',
  getParentRoute: () => PassportRoute,
} as any).lazy(() =>
  import('./routes/passport/find-account.lazy.tsx').then((d) => d.Route),
)
const AboutIntroductionRoute = AboutIntroductionRouteImport.update({
  id: '/about/introduction',
  path: '/about/introduction',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/about/introduction.lazy.tsx').then((d) => d.Route),
)
const AboutGuideRoute = AboutGuideRouteImport.update({
  id: '/about/guide',
  path: '/about/guide',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/about/guide.lazy.tsx').then((d) => d.Route),
)
const PassportVideo_backgroundRouteRoute =
  PassportVideo_backgroundRouteRouteImport.update({
    id: '/_video_background',
    getParentRoute: () => PassportRoute,
  } as any)
const SchoolWallIndexRoute = SchoolWallIndexRouteImport.update({
  id: '/wall/',
  path: '/wall/',
  getParentRoute: () => SchoolRouteRoute,
} as any)
const SchoolLiveIndexRoute = SchoolLiveIndexRouteImport.update({
  id: '/live/',
  path: '/live/',
  getParentRoute: () => SchoolRouteRoute,
} as any).lazy(() =>
  import('./routes/_school/live/index.lazy.tsx').then((d) => d.Route),
)
const PassportVideo_backgroundSignupRoute =
  PassportVideo_backgroundSignupRouteImport.update({
    id: '/signup',
    path: '/signup',
    getParentRoute: () => PassportVideo_backgroundRouteRoute,
  } as any).lazy(() =>
    import('./routes/passport/_video_background/signup.lazy.tsx').then(
      (d) => d.Route,
    ),
  )
const PassportVideo_backgroundLoginRoute =
  PassportVideo_backgroundLoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => PassportVideo_backgroundRouteRoute,
  } as any).lazy(() =>
    import('./routes/passport/_video_background/login.lazy.tsx').then(
      (d) => d.Route,
    ),
  )
const SchoolWallPublishRoute = SchoolWallPublishRouteImport.update({
  id: '/wall/publish',
  path: '/wall/publish',
  getParentRoute: () => SchoolRouteRoute,
} as any).lazy(() =>
  import('./routes/_school/wall/publish.lazy.tsx').then((d) => d.Route),
)
const SchoolProfileSecurityRoute = SchoolProfileSecurityRouteImport.update({
  id: '/profile/security',
  path: '/profile/security',
  getParentRoute: () => SchoolRouteRoute,
} as any)
const SchoolProfileCenterRoute = SchoolProfileCenterRouteImport.update({
  id: '/profile/center',
  path: '/profile/center',
  getParentRoute: () => SchoolRouteRoute,
} as any)
const SchoolExaminationSplatRoute = SchoolExaminationSplatRouteImport.update({
  id: '/examination/$',
  path: '/examination/$',
  getParentRoute: () => SchoolRouteRoute,
} as any)
const SchoolWallListRouteRoute = SchoolWallListRouteRouteImport.update({
  id: '/wall/list',
  path: '/wall/list',
  getParentRoute: () => SchoolRouteRoute,
} as any).lazy(() =>
  import('./routes/_school/wall/list/route.lazy.tsx').then((d) => d.Route),
)
const SchoolWallReviewIndexRoute = SchoolWallReviewIndexRouteImport.update({
  id: '/wall/review/',
  path: '/wall/review/',
  getParentRoute: () => SchoolRouteRoute,
} as any).lazy(() =>
  import('./routes/_school/wall/review/index.lazy.tsx').then((d) => d.Route),
)
const SchoolWallListChar123GroupIdChar125Route =
  SchoolWallListChar123GroupIdChar125RouteImport.update({
    id: '/{-$groupId}',
    path: '/{-$groupId}',
    getParentRoute: () => SchoolWallListRouteRoute,
  } as any).lazy(() =>
    import('./routes/_school/wall/list/{-$groupId}.lazy.tsx').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/empty': typeof EmptyRoute
  '/passport': typeof PassportVideo_backgroundRouteRouteWithChildren
  '/about/guide': typeof AboutGuideRoute
  '/about/introduction': typeof AboutIntroductionRoute
  '/passport/find-account': typeof PassportFindAccountRoute
  '/': typeof homeIndexRoute
  '/about': typeof AboutIndexRoute
  '/story': typeof StoryIndexRoute
  '/wall/list': typeof SchoolWallListRouteRouteWithChildren
  '/examination/$': typeof SchoolExaminationSplatRoute
  '/profile/center': typeof SchoolProfileCenterRoute
  '/profile/security': typeof SchoolProfileSecurityRoute
  '/wall/publish': typeof SchoolWallPublishRoute
  '/passport/login': typeof PassportVideo_backgroundLoginRoute
  '/passport/signup': typeof PassportVideo_backgroundSignupRoute
  '/live': typeof SchoolLiveIndexRoute
  '/wall': typeof SchoolWallIndexRoute
  '/wall/list/{-$groupId}': typeof SchoolWallListChar123GroupIdChar125Route
  '/wall/review': typeof SchoolWallReviewIndexRoute
}
export interface FileRoutesByTo {
  '/empty': typeof EmptyRoute
  '/passport': typeof PassportVideo_backgroundRouteRouteWithChildren
  '/about/guide': typeof AboutGuideRoute
  '/about/introduction': typeof AboutIntroductionRoute
  '/passport/find-account': typeof PassportFindAccountRoute
  '/': typeof homeIndexRoute
  '/about': typeof AboutIndexRoute
  '/story': typeof StoryIndexRoute
  '/wall/list': typeof SchoolWallListRouteRouteWithChildren
  '/examination/$': typeof SchoolExaminationSplatRoute
  '/profile/center': typeof SchoolProfileCenterRoute
  '/profile/security': typeof SchoolProfileSecurityRoute
  '/wall/publish': typeof SchoolWallPublishRoute
  '/passport/login': typeof PassportVideo_backgroundLoginRoute
  '/passport/signup': typeof PassportVideo_backgroundSignupRoute
  '/live': typeof SchoolLiveIndexRoute
  '/wall': typeof SchoolWallIndexRoute
  '/wall/list/{-$groupId}': typeof SchoolWallListChar123GroupIdChar125Route
  '/wall/review': typeof SchoolWallReviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_school': typeof SchoolRouteRouteWithChildren
  '/empty': typeof EmptyRoute
  '/passport': typeof PassportRouteWithChildren
  '/passport/_video_background': typeof PassportVideo_backgroundRouteRouteWithChildren
  '/about/guide': typeof AboutGuideRoute
  '/about/introduction': typeof AboutIntroductionRoute
  '/passport/find-account': typeof PassportFindAccountRoute
  '/(home)/': typeof homeIndexRoute
  '/about/': typeof AboutIndexRoute
  '/story/': typeof StoryIndexRoute
  '/_school/wall/list': typeof SchoolWallListRouteRouteWithChildren
  '/_school/examination/$': typeof SchoolExaminationSplatRoute
  '/_school/profile/center': typeof SchoolProfileCenterRoute
  '/_school/profile/security': typeof SchoolProfileSecurityRoute
  '/_school/wall/publish': typeof SchoolWallPublishRoute
  '/passport/_video_background/login': typeof PassportVideo_backgroundLoginRoute
  '/passport/_video_background/signup': typeof PassportVideo_backgroundSignupRoute
  '/_school/live/': typeof SchoolLiveIndexRoute
  '/_school/wall/': typeof SchoolWallIndexRoute
  '/_school/wall/list/{-$groupId}': typeof SchoolWallListChar123GroupIdChar125Route
  '/_school/wall/review/': typeof SchoolWallReviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/empty'
    | '/passport'
    | '/about/guide'
    | '/about/introduction'
    | '/passport/find-account'
    | '/'
    | '/about'
    | '/story'
    | '/wall/list'
    | '/examination/$'
    | '/profile/center'
    | '/profile/security'
    | '/wall/publish'
    | '/passport/login'
    | '/passport/signup'
    | '/live'
    | '/wall'
    | '/wall/list/{-$groupId}'
    | '/wall/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/empty'
    | '/passport'
    | '/about/guide'
    | '/about/introduction'
    | '/passport/find-account'
    | '/'
    | '/about'
    | '/story'
    | '/wall/list'
    | '/examination/$'
    | '/profile/center'
    | '/profile/security'
    | '/wall/publish'
    | '/passport/login'
    | '/passport/signup'
    | '/live'
    | '/wall'
    | '/wall/list/{-$groupId}'
    | '/wall/review'
  id:
    | '__root__'
    | '/_school'
    | '/empty'
    | '/passport'
    | '/passport/_video_background'
    | '/about/guide'
    | '/about/introduction'
    | '/passport/find-account'
    | '/(home)/'
    | '/about/'
    | '/story/'
    | '/_school/wall/list'
    | '/_school/examination/$'
    | '/_school/profile/center'
    | '/_school/profile/security'
    | '/_school/wall/publish'
    | '/passport/_video_background/login'
    | '/passport/_video_background/signup'
    | '/_school/live/'
    | '/_school/wall/'
    | '/_school/wall/list/{-$groupId}'
    | '/_school/wall/review/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SchoolRouteRoute: typeof SchoolRouteRouteWithChildren
  EmptyRoute: typeof EmptyRoute
  PassportRoute: typeof PassportRouteWithChildren
  AboutGuideRoute: typeof AboutGuideRoute
  AboutIntroductionRoute: typeof AboutIntroductionRoute
  homeIndexRoute: typeof homeIndexRoute
  AboutIndexRoute: typeof AboutIndexRoute
  StoryIndexRoute: typeof StoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/passport': {
      id: '/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof PassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empty': {
      id: '/empty'
      path: '/empty'
      fullPath: '/empty'
      preLoaderRoute: typeof EmptyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_school': {
      id: '/_school'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SchoolRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/': {
      id: '/story/'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport/find-account': {
      id: '/passport/find-account'
      path: '/find-account'
      fullPath: '/passport/find-account'
      preLoaderRoute: typeof PassportFindAccountRouteImport
      parentRoute: typeof PassportRoute
    }
    '/about/introduction': {
      id: '/about/introduction'
      path: '/about/introduction'
      fullPath: '/about/introduction'
      preLoaderRoute: typeof AboutIntroductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/guide': {
      id: '/about/guide'
      path: '/about/guide'
      fullPath: '/about/guide'
      preLoaderRoute: typeof AboutGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport/_video_background': {
      id: '/passport/_video_background'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof PassportVideo_backgroundRouteRouteImport
      parentRoute: typeof PassportRoute
    }
    '/_school/wall/': {
      id: '/_school/wall/'
      path: '/wall'
      fullPath: '/wall'
      preLoaderRoute: typeof SchoolWallIndexRouteImport
      parentRoute: typeof SchoolRouteRoute
    }
    '/_school/live/': {
      id: '/_school/live/'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof SchoolLiveIndexRouteImport
      parentRoute: typeof SchoolRouteRoute
    }
    '/passport/_video_background/signup': {
      id: '/passport/_video_background/signup'
      path: '/signup'
      fullPath: '/passport/signup'
      preLoaderRoute: typeof PassportVideo_backgroundSignupRouteImport
      parentRoute: typeof PassportVideo_backgroundRouteRoute
    }
    '/passport/_video_background/login': {
      id: '/passport/_video_background/login'
      path: '/login'
      fullPath: '/passport/login'
      preLoaderRoute: typeof PassportVideo_backgroundLoginRouteImport
      parentRoute: typeof PassportVideo_backgroundRouteRoute
    }
    '/_school/wall/publish': {
      id: '/_school/wall/publish'
      path: '/wall/publish'
      fullPath: '/wall/publish'
      preLoaderRoute: typeof SchoolWallPublishRouteImport
      parentRoute: typeof SchoolRouteRoute
    }
    '/_school/profile/security': {
      id: '/_school/profile/security'
      path: '/profile/security'
      fullPath: '/profile/security'
      preLoaderRoute: typeof SchoolProfileSecurityRouteImport
      parentRoute: typeof SchoolRouteRoute
    }
    '/_school/profile/center': {
      id: '/_school/profile/center'
      path: '/profile/center'
      fullPath: '/profile/center'
      preLoaderRoute: typeof SchoolProfileCenterRouteImport
      parentRoute: typeof SchoolRouteRoute
    }
    '/_school/examination/$': {
      id: '/_school/examination/$'
      path: '/examination/$'
      fullPath: '/examination/$'
      preLoaderRoute: typeof SchoolExaminationSplatRouteImport
      parentRoute: typeof SchoolRouteRoute
    }
    '/_school/wall/list': {
      id: '/_school/wall/list'
      path: '/wall/list'
      fullPath: '/wall/list'
      preLoaderRoute: typeof SchoolWallListRouteRouteImport
      parentRoute: typeof SchoolRouteRoute
    }
    '/_school/wall/review/': {
      id: '/_school/wall/review/'
      path: '/wall/review'
      fullPath: '/wall/review'
      preLoaderRoute: typeof SchoolWallReviewIndexRouteImport
      parentRoute: typeof SchoolRouteRoute
    }
    '/_school/wall/list/{-$groupId}': {
      id: '/_school/wall/list/{-$groupId}'
      path: '/{-$groupId}'
      fullPath: '/wall/list/{-$groupId}'
      preLoaderRoute: typeof SchoolWallListChar123GroupIdChar125RouteImport
      parentRoute: typeof SchoolWallListRouteRoute
    }
  }
}

interface SchoolWallListRouteRouteChildren {
  SchoolWallListChar123GroupIdChar125Route: typeof SchoolWallListChar123GroupIdChar125Route
}

const SchoolWallListRouteRouteChildren: SchoolWallListRouteRouteChildren = {
  SchoolWallListChar123GroupIdChar125Route:
    SchoolWallListChar123GroupIdChar125Route,
}

const SchoolWallListRouteRouteWithChildren =
  SchoolWallListRouteRoute._addFileChildren(SchoolWallListRouteRouteChildren)

interface SchoolRouteRouteChildren {
  SchoolWallListRouteRoute: typeof SchoolWallListRouteRouteWithChildren
  SchoolExaminationSplatRoute: typeof SchoolExaminationSplatRoute
  SchoolProfileCenterRoute: typeof SchoolProfileCenterRoute
  SchoolProfileSecurityRoute: typeof SchoolProfileSecurityRoute
  SchoolWallPublishRoute: typeof SchoolWallPublishRoute
  SchoolLiveIndexRoute: typeof SchoolLiveIndexRoute
  SchoolWallIndexRoute: typeof SchoolWallIndexRoute
  SchoolWallReviewIndexRoute: typeof SchoolWallReviewIndexRoute
}

const SchoolRouteRouteChildren: SchoolRouteRouteChildren = {
  SchoolWallListRouteRoute: SchoolWallListRouteRouteWithChildren,
  SchoolExaminationSplatRoute: SchoolExaminationSplatRoute,
  SchoolProfileCenterRoute: SchoolProfileCenterRoute,
  SchoolProfileSecurityRoute: SchoolProfileSecurityRoute,
  SchoolWallPublishRoute: SchoolWallPublishRoute,
  SchoolLiveIndexRoute: SchoolLiveIndexRoute,
  SchoolWallIndexRoute: SchoolWallIndexRoute,
  SchoolWallReviewIndexRoute: SchoolWallReviewIndexRoute,
}

const SchoolRouteRouteWithChildren = SchoolRouteRoute._addFileChildren(
  SchoolRouteRouteChildren,
)

interface PassportVideo_backgroundRouteRouteChildren {
  PassportVideo_backgroundLoginRoute: typeof PassportVideo_backgroundLoginRoute
  PassportVideo_backgroundSignupRoute: typeof PassportVideo_backgroundSignupRoute
}

const PassportVideo_backgroundRouteRouteChildren: PassportVideo_backgroundRouteRouteChildren =
  {
    PassportVideo_backgroundLoginRoute: PassportVideo_backgroundLoginRoute,
    PassportVideo_backgroundSignupRoute: PassportVideo_backgroundSignupRoute,
  }

const PassportVideo_backgroundRouteRouteWithChildren =
  PassportVideo_backgroundRouteRoute._addFileChildren(
    PassportVideo_backgroundRouteRouteChildren,
  )

interface PassportRouteChildren {
  PassportVideo_backgroundRouteRoute: typeof PassportVideo_backgroundRouteRouteWithChildren
  PassportFindAccountRoute: typeof PassportFindAccountRoute
}

const PassportRouteChildren: PassportRouteChildren = {
  PassportVideo_backgroundRouteRoute:
    PassportVideo_backgroundRouteRouteWithChildren,
  PassportFindAccountRoute: PassportFindAccountRoute,
}

const PassportRouteWithChildren = PassportRoute._addFileChildren(
  PassportRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SchoolRouteRoute: SchoolRouteRouteWithChildren,
  EmptyRoute: EmptyRoute,
  PassportRoute: PassportRouteWithChildren,
  AboutGuideRoute: AboutGuideRoute,
  AboutIntroductionRoute: AboutIntroductionRoute,
  homeIndexRoute: homeIndexRoute,
  AboutIndexRoute: AboutIndexRoute,
  StoryIndexRoute: StoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
