/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root.tsx'
import { Route as ThemeRouteRouteImport } from './routes/_theme/route.tsx'
import { Route as SchoolRouteRouteImport } from './routes/_school/route.tsx'
import { Route as StoryIndexRouteImport } from './routes/story/index.tsx'
import { Route as homeIndexRouteImport } from './routes/(home)/index.tsx'
import { Route as ThemeAboutIndexRouteImport } from './routes/_theme/about/index.tsx'
import { Route as SchoolWallIndexRouteImport } from './routes/_school/wall/index.tsx'
import { Route as SchoolLiveIndexRouteImport } from './routes/_school/live/index.tsx'
import { Route as ThemePassportFindAccountRouteImport } from './routes/_theme/passport/find-account.tsx'
import { Route as ThemeAboutIntroductionRouteImport } from './routes/_theme/about/introduction.tsx'
import { Route as ThemeAboutGuideRouteImport } from './routes/_theme/about/guide.tsx'
import { Route as SchoolWallPublishRouteImport } from './routes/_school/wall/publish.tsx'
import { Route as SchoolProfileSecurityRouteImport } from './routes/_school/profile/security.tsx'
import { Route as SchoolProfileCenterRouteImport } from './routes/_school/profile/center.tsx'
import { Route as SchoolExaminationSplatRouteImport } from './routes/_school/examination/$.tsx'
import { Route as ThemePassportVideo_backgroundRouteRouteImport } from './routes/_theme/passport/_video_background/route.tsx'
import { Route as SchoolWallReviewIndexRouteImport } from './routes/_school/wall/review/index.tsx'
import { Route as ThemePassportVideo_backgroundSignupRouteImport } from './routes/_theme/passport/_video_background/signup.tsx'
import { Route as ThemePassportVideo_backgroundLoginRouteImport } from './routes/_theme/passport/_video_background/login.tsx'
import { Route as SchoolWallListChar123GroupIdChar125RouteRouteImport } from './routes/_school/wall/list.{-$groupId}/route.tsx'
import { Route as SchoolWallListChar123GroupIdChar125IndexRouteImport } from './routes/_school/wall/list.{-$groupId}/index.tsx'

const ThemePassportRouteImport = createFileRoute('/_theme/passport')()

const ThemeRouteRoute = ThemeRouteRouteImport.update({
  id: '/_theme',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/_theme/route.lazy.tsx').then((d) => d.Route),
)
const SchoolRouteRoute = SchoolRouteRouteImport.update({
  id: '/_school',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/_school/route.lazy.tsx').then((d) => d.Route),
)
const ThemePassportRoute = ThemePassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => ThemeRouteRoute,
} as any)
const StoryIndexRoute = StoryIndexRouteImport.update({
  id: '/story/',
  path: '/story/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/story/index.lazy.tsx').then((d) => d.Route),
)
const homeIndexRoute = homeIndexRouteImport
  .update({
    id: '/(home)/',
    path: '/',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(home)/index.lazy.tsx').then((d) => d.Route))
const ThemeAboutIndexRoute = ThemeAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => ThemeRouteRoute,
} as any).lazy(() =>
  import('./routes/_theme/about/index.lazy.tsx').then((d) => d.Route),
)
const SchoolWallIndexRoute = SchoolWallIndexRouteImport.update({
  id: '/wall/',
  path: '/wall/',
  getParentRoute: () => SchoolRouteRoute,
} as any)
const SchoolLiveIndexRoute = SchoolLiveIndexRouteImport.update({
  id: '/live/',
  path: '/live/',
  getParentRoute: () => SchoolRouteRoute,
} as any).lazy(() =>
  import('./routes/_school/live/index.lazy.tsx').then((d) => d.Route),
)
const ThemePassportFindAccountRoute =
  ThemePassportFindAccountRouteImport.update({
    id: '/find-account',
    path: '/find-account',
    getParentRoute: () => ThemePassportRoute,
  } as any).lazy(() =>
    import('./routes/_theme/passport/find-account.lazy.tsx').then(
      (d) => d.Route,
    ),
  )
const ThemeAboutIntroductionRoute = ThemeAboutIntroductionRouteImport.update({
  id: '/about/introduction',
  path: '/about/introduction',
  getParentRoute: () => ThemeRouteRoute,
} as any).lazy(() =>
  import('./routes/_theme/about/introduction.lazy.tsx').then((d) => d.Route),
)
const ThemeAboutGuideRoute = ThemeAboutGuideRouteImport.update({
  id: '/about/guide',
  path: '/about/guide',
  getParentRoute: () => ThemeRouteRoute,
} as any).lazy(() =>
  import('./routes/_theme/about/guide.lazy.tsx').then((d) => d.Route),
)
const SchoolWallPublishRoute = SchoolWallPublishRouteImport.update({
  id: '/wall/publish',
  path: '/wall/publish',
  getParentRoute: () => SchoolRouteRoute,
} as any).lazy(() =>
  import('./routes/_school/wall/publish.lazy.tsx').then((d) => d.Route),
)
const SchoolProfileSecurityRoute = SchoolProfileSecurityRouteImport.update({
  id: '/profile/security',
  path: '/profile/security',
  getParentRoute: () => SchoolRouteRoute,
} as any).lazy(() =>
  import('./routes/_school/profile/security.lazy.tsx').then((d) => d.Route),
)
const SchoolProfileCenterRoute = SchoolProfileCenterRouteImport.update({
  id: '/profile/center',
  path: '/profile/center',
  getParentRoute: () => SchoolRouteRoute,
} as any).lazy(() =>
  import('./routes/_school/profile/center.lazy.tsx').then((d) => d.Route),
)
const SchoolExaminationSplatRoute = SchoolExaminationSplatRouteImport.update({
  id: '/examination/$',
  path: '/examination/$',
  getParentRoute: () => SchoolRouteRoute,
} as any)
const ThemePassportVideo_backgroundRouteRoute =
  ThemePassportVideo_backgroundRouteRouteImport.update({
    id: '/_video_background',
    getParentRoute: () => ThemePassportRoute,
  } as any)
const SchoolWallReviewIndexRoute = SchoolWallReviewIndexRouteImport.update({
  id: '/wall/review/',
  path: '/wall/review/',
  getParentRoute: () => SchoolRouteRoute,
} as any).lazy(() =>
  import('./routes/_school/wall/review/index.lazy.tsx').then((d) => d.Route),
)
const ThemePassportVideo_backgroundSignupRoute =
  ThemePassportVideo_backgroundSignupRouteImport.update({
    id: '/signup',
    path: '/signup',
    getParentRoute: () => ThemePassportVideo_backgroundRouteRoute,
  } as any).lazy(() =>
    import('./routes/_theme/passport/_video_background/signup.lazy.tsx').then(
      (d) => d.Route,
    ),
  )
const ThemePassportVideo_backgroundLoginRoute =
  ThemePassportVideo_backgroundLoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => ThemePassportVideo_backgroundRouteRoute,
  } as any).lazy(() =>
    import('./routes/_theme/passport/_video_background/login.lazy.tsx').then(
      (d) => d.Route,
    ),
  )
const SchoolWallListChar123GroupIdChar125RouteRoute =
  SchoolWallListChar123GroupIdChar125RouteRouteImport.update({
    id: '/wall/list/{-$groupId}',
    path: '/wall/list/{-$groupId}',
    getParentRoute: () => SchoolRouteRoute,
  } as any).lazy(() =>
    import('./routes/_school/wall/list.{-$groupId}/route.lazy.tsx').then(
      (d) => d.Route,
    ),
  )
const SchoolWallListChar123GroupIdChar125IndexRoute =
  SchoolWallListChar123GroupIdChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SchoolWallListChar123GroupIdChar125RouteRoute,
  } as any).lazy(() =>
    import('./routes/_school/wall/list.{-$groupId}/index.lazy.tsx').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof homeIndexRoute
  '/story': typeof StoryIndexRoute
  '/passport': typeof ThemePassportVideo_backgroundRouteRouteWithChildren
  '/examination/$': typeof SchoolExaminationSplatRoute
  '/profile/center': typeof SchoolProfileCenterRoute
  '/profile/security': typeof SchoolProfileSecurityRoute
  '/wall/publish': typeof SchoolWallPublishRoute
  '/about/guide': typeof ThemeAboutGuideRoute
  '/about/introduction': typeof ThemeAboutIntroductionRoute
  '/passport/find-account': typeof ThemePassportFindAccountRoute
  '/live': typeof SchoolLiveIndexRoute
  '/wall': typeof SchoolWallIndexRoute
  '/about': typeof ThemeAboutIndexRoute
  '/wall/list/{-$groupId}': typeof SchoolWallListChar123GroupIdChar125RouteRouteWithChildren
  '/passport/login': typeof ThemePassportVideo_backgroundLoginRoute
  '/passport/signup': typeof ThemePassportVideo_backgroundSignupRoute
  '/wall/review': typeof SchoolWallReviewIndexRoute
  '/wall/list/{-$groupId}/': typeof SchoolWallListChar123GroupIdChar125IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof homeIndexRoute
  '/story': typeof StoryIndexRoute
  '/passport': typeof ThemePassportVideo_backgroundRouteRouteWithChildren
  '/examination/$': typeof SchoolExaminationSplatRoute
  '/profile/center': typeof SchoolProfileCenterRoute
  '/profile/security': typeof SchoolProfileSecurityRoute
  '/wall/publish': typeof SchoolWallPublishRoute
  '/about/guide': typeof ThemeAboutGuideRoute
  '/about/introduction': typeof ThemeAboutIntroductionRoute
  '/passport/find-account': typeof ThemePassportFindAccountRoute
  '/live': typeof SchoolLiveIndexRoute
  '/wall': typeof SchoolWallIndexRoute
  '/about': typeof ThemeAboutIndexRoute
  '/passport/login': typeof ThemePassportVideo_backgroundLoginRoute
  '/passport/signup': typeof ThemePassportVideo_backgroundSignupRoute
  '/wall/review': typeof SchoolWallReviewIndexRoute
  '/wall/list/{-$groupId}': typeof SchoolWallListChar123GroupIdChar125IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_school': typeof SchoolRouteRouteWithChildren
  '/_theme': typeof ThemeRouteRouteWithChildren
  '/(home)/': typeof homeIndexRoute
  '/story/': typeof StoryIndexRoute
  '/_theme/passport': typeof ThemePassportRouteWithChildren
  '/_theme/passport/_video_background': typeof ThemePassportVideo_backgroundRouteRouteWithChildren
  '/_school/examination/$': typeof SchoolExaminationSplatRoute
  '/_school/profile/center': typeof SchoolProfileCenterRoute
  '/_school/profile/security': typeof SchoolProfileSecurityRoute
  '/_school/wall/publish': typeof SchoolWallPublishRoute
  '/_theme/about/guide': typeof ThemeAboutGuideRoute
  '/_theme/about/introduction': typeof ThemeAboutIntroductionRoute
  '/_theme/passport/find-account': typeof ThemePassportFindAccountRoute
  '/_school/live/': typeof SchoolLiveIndexRoute
  '/_school/wall/': typeof SchoolWallIndexRoute
  '/_theme/about/': typeof ThemeAboutIndexRoute
  '/_school/wall/list/{-$groupId}': typeof SchoolWallListChar123GroupIdChar125RouteRouteWithChildren
  '/_theme/passport/_video_background/login': typeof ThemePassportVideo_backgroundLoginRoute
  '/_theme/passport/_video_background/signup': typeof ThemePassportVideo_backgroundSignupRoute
  '/_school/wall/review/': typeof SchoolWallReviewIndexRoute
  '/_school/wall/list/{-$groupId}/': typeof SchoolWallListChar123GroupIdChar125IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/story'
    | '/passport'
    | '/examination/$'
    | '/profile/center'
    | '/profile/security'
    | '/wall/publish'
    | '/about/guide'
    | '/about/introduction'
    | '/passport/find-account'
    | '/live'
    | '/wall'
    | '/about'
    | '/wall/list/{-$groupId}'
    | '/passport/login'
    | '/passport/signup'
    | '/wall/review'
    | '/wall/list/{-$groupId}/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/story'
    | '/passport'
    | '/examination/$'
    | '/profile/center'
    | '/profile/security'
    | '/wall/publish'
    | '/about/guide'
    | '/about/introduction'
    | '/passport/find-account'
    | '/live'
    | '/wall'
    | '/about'
    | '/passport/login'
    | '/passport/signup'
    | '/wall/review'
    | '/wall/list/{-$groupId}'
  id:
    | '__root__'
    | '/_school'
    | '/_theme'
    | '/(home)/'
    | '/story/'
    | '/_theme/passport'
    | '/_theme/passport/_video_background'
    | '/_school/examination/$'
    | '/_school/profile/center'
    | '/_school/profile/security'
    | '/_school/wall/publish'
    | '/_theme/about/guide'
    | '/_theme/about/introduction'
    | '/_theme/passport/find-account'
    | '/_school/live/'
    | '/_school/wall/'
    | '/_theme/about/'
    | '/_school/wall/list/{-$groupId}'
    | '/_theme/passport/_video_background/login'
    | '/_theme/passport/_video_background/signup'
    | '/_school/wall/review/'
    | '/_school/wall/list/{-$groupId}/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SchoolRouteRoute: typeof SchoolRouteRouteWithChildren
  ThemeRouteRoute: typeof ThemeRouteRouteWithChildren
  homeIndexRoute: typeof homeIndexRoute
  StoryIndexRoute: typeof StoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_theme': {
      id: '/_theme'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ThemeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_school': {
      id: '/_school'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SchoolRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_theme/passport': {
      id: '/_theme/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof ThemePassportRouteImport
      parentRoute: typeof ThemeRouteRoute
    }
    '/story/': {
      id: '/story/'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_theme/about/': {
      id: '/_theme/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof ThemeAboutIndexRouteImport
      parentRoute: typeof ThemeRouteRoute
    }
    '/_school/wall/': {
      id: '/_school/wall/'
      path: '/wall'
      fullPath: '/wall'
      preLoaderRoute: typeof SchoolWallIndexRouteImport
      parentRoute: typeof SchoolRouteRoute
    }
    '/_school/live/': {
      id: '/_school/live/'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof SchoolLiveIndexRouteImport
      parentRoute: typeof SchoolRouteRoute
    }
    '/_theme/passport/find-account': {
      id: '/_theme/passport/find-account'
      path: '/find-account'
      fullPath: '/passport/find-account'
      preLoaderRoute: typeof ThemePassportFindAccountRouteImport
      parentRoute: typeof ThemePassportRoute
    }
    '/_theme/about/introduction': {
      id: '/_theme/about/introduction'
      path: '/about/introduction'
      fullPath: '/about/introduction'
      preLoaderRoute: typeof ThemeAboutIntroductionRouteImport
      parentRoute: typeof ThemeRouteRoute
    }
    '/_theme/about/guide': {
      id: '/_theme/about/guide'
      path: '/about/guide'
      fullPath: '/about/guide'
      preLoaderRoute: typeof ThemeAboutGuideRouteImport
      parentRoute: typeof ThemeRouteRoute
    }
    '/_school/wall/publish': {
      id: '/_school/wall/publish'
      path: '/wall/publish'
      fullPath: '/wall/publish'
      preLoaderRoute: typeof SchoolWallPublishRouteImport
      parentRoute: typeof SchoolRouteRoute
    }
    '/_school/profile/security': {
      id: '/_school/profile/security'
      path: '/profile/security'
      fullPath: '/profile/security'
      preLoaderRoute: typeof SchoolProfileSecurityRouteImport
      parentRoute: typeof SchoolRouteRoute
    }
    '/_school/profile/center': {
      id: '/_school/profile/center'
      path: '/profile/center'
      fullPath: '/profile/center'
      preLoaderRoute: typeof SchoolProfileCenterRouteImport
      parentRoute: typeof SchoolRouteRoute
    }
    '/_school/examination/$': {
      id: '/_school/examination/$'
      path: '/examination/$'
      fullPath: '/examination/$'
      preLoaderRoute: typeof SchoolExaminationSplatRouteImport
      parentRoute: typeof SchoolRouteRoute
    }
    '/_theme/passport/_video_background': {
      id: '/_theme/passport/_video_background'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof ThemePassportVideo_backgroundRouteRouteImport
      parentRoute: typeof ThemePassportRoute
    }
    '/_school/wall/review/': {
      id: '/_school/wall/review/'
      path: '/wall/review'
      fullPath: '/wall/review'
      preLoaderRoute: typeof SchoolWallReviewIndexRouteImport
      parentRoute: typeof SchoolRouteRoute
    }
    '/_theme/passport/_video_background/signup': {
      id: '/_theme/passport/_video_background/signup'
      path: '/signup'
      fullPath: '/passport/signup'
      preLoaderRoute: typeof ThemePassportVideo_backgroundSignupRouteImport
      parentRoute: typeof ThemePassportVideo_backgroundRouteRoute
    }
    '/_theme/passport/_video_background/login': {
      id: '/_theme/passport/_video_background/login'
      path: '/login'
      fullPath: '/passport/login'
      preLoaderRoute: typeof ThemePassportVideo_backgroundLoginRouteImport
      parentRoute: typeof ThemePassportVideo_backgroundRouteRoute
    }
    '/_school/wall/list/{-$groupId}': {
      id: '/_school/wall/list/{-$groupId}'
      path: '/wall/list/{-$groupId}'
      fullPath: '/wall/list/{-$groupId}'
      preLoaderRoute: typeof SchoolWallListChar123GroupIdChar125RouteRouteImport
      parentRoute: typeof SchoolRouteRoute
    }
    '/_school/wall/list/{-$groupId}/': {
      id: '/_school/wall/list/{-$groupId}/'
      path: '/'
      fullPath: '/wall/list/{-$groupId}/'
      preLoaderRoute: typeof SchoolWallListChar123GroupIdChar125IndexRouteImport
      parentRoute: typeof SchoolWallListChar123GroupIdChar125RouteRoute
    }
  }
}

interface SchoolWallListChar123GroupIdChar125RouteRouteChildren {
  SchoolWallListChar123GroupIdChar125IndexRoute: typeof SchoolWallListChar123GroupIdChar125IndexRoute
}

const SchoolWallListChar123GroupIdChar125RouteRouteChildren: SchoolWallListChar123GroupIdChar125RouteRouteChildren =
  {
    SchoolWallListChar123GroupIdChar125IndexRoute:
      SchoolWallListChar123GroupIdChar125IndexRoute,
  }

const SchoolWallListChar123GroupIdChar125RouteRouteWithChildren =
  SchoolWallListChar123GroupIdChar125RouteRoute._addFileChildren(
    SchoolWallListChar123GroupIdChar125RouteRouteChildren,
  )

interface SchoolRouteRouteChildren {
  SchoolExaminationSplatRoute: typeof SchoolExaminationSplatRoute
  SchoolProfileCenterRoute: typeof SchoolProfileCenterRoute
  SchoolProfileSecurityRoute: typeof SchoolProfileSecurityRoute
  SchoolWallPublishRoute: typeof SchoolWallPublishRoute
  SchoolLiveIndexRoute: typeof SchoolLiveIndexRoute
  SchoolWallIndexRoute: typeof SchoolWallIndexRoute
  SchoolWallListChar123GroupIdChar125RouteRoute: typeof SchoolWallListChar123GroupIdChar125RouteRouteWithChildren
  SchoolWallReviewIndexRoute: typeof SchoolWallReviewIndexRoute
}

const SchoolRouteRouteChildren: SchoolRouteRouteChildren = {
  SchoolExaminationSplatRoute: SchoolExaminationSplatRoute,
  SchoolProfileCenterRoute: SchoolProfileCenterRoute,
  SchoolProfileSecurityRoute: SchoolProfileSecurityRoute,
  SchoolWallPublishRoute: SchoolWallPublishRoute,
  SchoolLiveIndexRoute: SchoolLiveIndexRoute,
  SchoolWallIndexRoute: SchoolWallIndexRoute,
  SchoolWallListChar123GroupIdChar125RouteRoute:
    SchoolWallListChar123GroupIdChar125RouteRouteWithChildren,
  SchoolWallReviewIndexRoute: SchoolWallReviewIndexRoute,
}

const SchoolRouteRouteWithChildren = SchoolRouteRoute._addFileChildren(
  SchoolRouteRouteChildren,
)

interface ThemePassportVideo_backgroundRouteRouteChildren {
  ThemePassportVideo_backgroundLoginRoute: typeof ThemePassportVideo_backgroundLoginRoute
  ThemePassportVideo_backgroundSignupRoute: typeof ThemePassportVideo_backgroundSignupRoute
}

const ThemePassportVideo_backgroundRouteRouteChildren: ThemePassportVideo_backgroundRouteRouteChildren =
  {
    ThemePassportVideo_backgroundLoginRoute:
      ThemePassportVideo_backgroundLoginRoute,
    ThemePassportVideo_backgroundSignupRoute:
      ThemePassportVideo_backgroundSignupRoute,
  }

const ThemePassportVideo_backgroundRouteRouteWithChildren =
  ThemePassportVideo_backgroundRouteRoute._addFileChildren(
    ThemePassportVideo_backgroundRouteRouteChildren,
  )

interface ThemePassportRouteChildren {
  ThemePassportVideo_backgroundRouteRoute: typeof ThemePassportVideo_backgroundRouteRouteWithChildren
  ThemePassportFindAccountRoute: typeof ThemePassportFindAccountRoute
}

const ThemePassportRouteChildren: ThemePassportRouteChildren = {
  ThemePassportVideo_backgroundRouteRoute:
    ThemePassportVideo_backgroundRouteRouteWithChildren,
  ThemePassportFindAccountRoute: ThemePassportFindAccountRoute,
}

const ThemePassportRouteWithChildren = ThemePassportRoute._addFileChildren(
  ThemePassportRouteChildren,
)

interface ThemeRouteRouteChildren {
  ThemePassportRoute: typeof ThemePassportRouteWithChildren
  ThemeAboutGuideRoute: typeof ThemeAboutGuideRoute
  ThemeAboutIntroductionRoute: typeof ThemeAboutIntroductionRoute
  ThemeAboutIndexRoute: typeof ThemeAboutIndexRoute
}

const ThemeRouteRouteChildren: ThemeRouteRouteChildren = {
  ThemePassportRoute: ThemePassportRouteWithChildren,
  ThemeAboutGuideRoute: ThemeAboutGuideRoute,
  ThemeAboutIntroductionRoute: ThemeAboutIntroductionRoute,
  ThemeAboutIndexRoute: ThemeAboutIndexRoute,
}

const ThemeRouteRouteWithChildren = ThemeRouteRoute._addFileChildren(
  ThemeRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SchoolRouteRoute: SchoolRouteRouteWithChildren,
  ThemeRouteRoute: ThemeRouteRouteWithChildren,
  homeIndexRoute: homeIndexRoute,
  StoryIndexRoute: StoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
