name: CI
on:
  push:
    branches:
      - "*"
      - "*/*"
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          ssh-key: ${{secrets.MOSS_SERVER_PKEY}}
      - name: Install
        uses: ./.github/actions/install-deps
      - run: pnpm init-deps
      - run: pnpm check-type
      - run: pnpm check-fmt
