name: Deploy WEB
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    env:
      WEB_ARTIFACT_NAME: web_dist-${{ github.sha }}
    steps:
      - uses: actions/checkout@v6
      - name: Setup project
        uses: ./.github/actions/setup-project
      - name: Build
        run: pnpm build
        env:
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          VITE_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

        working-directory: ./web
      - name: Upload artifacts
        id: upload_artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.WEB_ARTIFACT_NAME }}
          path: ./web/dist
          overwrite: true

      - uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.WEB_DEPLOY_HOST }}
          key: ${{ secrets.WEB_DEPLOY_KEY }}
          username: ${{ secrets.WEB_DEPLOY_USER }}
          script: |
            cd ${{ secrets.WEB_DEPLOY_PATH }}
            ./deploy_web.sh ${{ steps.upload_artifact.outputs['artifact-id'] }} ${{github.sha}}
