name: E2E Test
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build-images:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6

      - name: Build web images
        run: docker compose build web-nginx web-api

      - name: Export web-nginx image
        run: docker save -o web-nginx.tar ijia/web-nginx

      - uses: actions/upload-artifact@v7
        with:
          name: web-nginx-image-${{ github.sha }}
          path: web-nginx.tar
          overwrite: true

      - name: Export web-api image
        run: docker save -o web-api.tar ijia/web-api

      - uses: actions/upload-artifact@v7
        with:
          name: web-api-image-${{ github.sha }}
          path: web-api.tar
          overwrite: true

  e2e:
    runs-on: ubuntu-22.04
    needs: build-images
    steps:
      - uses: actions/checkout@v6
      - name: Setup project
        uses: ./.github/actions/setup-project
      - uses: actions/cache@v4 #https://playwright.dev/docs/browsers#managing-browser-binaries
        with:
          path: /home/runner/.cache/ms-playwright
          key: playwright-browser-${{ hashFiles('e2e/package.json') }}
      - name: Install browser
        run: pnpm playwright install chromium webkit firefox --with-deps
        working-directory: ./e2e

      - uses: actions/download-artifact@v4
        with:
          name: web-nginx-image-${{ github.sha }}

      - name: Load web-nginx image
        run: docker load -i web-nginx.tar

      - uses: actions/download-artifact@v4
        with:
          name: web-api-image-${{ github.sha }}

      - name: Load web-api image
        run: docker load -i web-api.tar

      - name: Build remaining local services
        run: docker compose build database

      - name: Start services
        run: docker compose up -d
      - name: E2E test
        continue-on-error: true
        run: pnpm run e2e:ci
        env:
          DATABASE_URL: "postgresql://postgres@localhost:5442/ijia"
          WEB_URL: "http://localhost:9002"
        id: e2e
        working-directory: ./e2e

      - uses: actions/upload-artifact@v7
        if: ${{steps.e2e.outcome=='failure'}}
        with:
          name: playwright-report
          path: e2e/playwright-report/
      - name: Result
        if: ${{steps.e2e.outcome=='failure'}}
        run: exit 1
