name: CI
on:
  pull_request:
    branches:
      - main
  push:
    paths:
      - e2e/**
      - web/**
      - web_api/**
      - pnpm-lock.yaml
      - .gitmodules
jobs:
  e2e:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          ssh-key: ${{secrets.MOSS_SERVER_PKEY}}
      - name: Build
        run: docker compose build
      - name: Install browser
        run: pnpm playwright install chromium webkit firefox --with-deps
        working-directory: ./e2e
      - name: Start services
        run: docker compose up -d
      - name: E2E test
        continue-on-error: true
        run: pnpm run ci:e2e
        id: e2e
        working-directory: ./e2e
      - uses: actions/upload-artifact@v4
        if: ${{steps.e2e.outcome=='failure'}}
        with:
          name: playwright-report
          path: e2e/playwright-report/
      - name: Result
        if: ${{steps.e2e.outcome=='failure'}}
        run: exit
