name: hono-decorator
on:
  push:
    branches:
      - "**"
    paths:
      - web_api/src/hono-decorator/**
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup project
        uses: ./.github/actions/setup-project
      - name: Test
        run: pnpm test
        working-directory: ./web_api/src/hono-decorator
